// Package template generates the documented YAML skeleton written by gaal init.
// It introspects the config structs via [Reflect] so that field names,
// descriptions, enums, and required/optional annotations stay in sync with
// the runtime types automatically — without any manual update.
package template

import (
	"bytes"
	"fmt"
	"log/slog"
	"reflect"
	"sort"
	"strings"

	"github.com/positron-ai/gaal/internal/config"
	"github.com/positron-ai/gaal/internal/core/agent"
)

const separator = "# ─────────────────────────────────────────────────────────────────────────────"

// scopeLabel returns the human-readable scope name for the file header.
func scopeLabel(scope config.ConfigScope) string {
	switch scope {
	case config.ScopeGlobal:
		return "Global"
	case config.ScopeUser:
		return "User"
	default:
		return "Workspace"
	}
}

// buildIntro returns the file header with the scope annotation injected.
// For Workspace scope the header describes all three resource sections;
// for User and Global scopes only gaal behaviour settings are mentioned.
func buildIntro(scope config.ConfigScope) string {
	var body string
	if scope == config.ScopeWorkspace {
		body = `# Manage three types of local resources from this single file:
#   repositories  — clone / update multi-protocol VCS repos
#   skills        — install SKILL.md collections into AI agent directories
#   mcps          — upsert MCP server entries into agent JSON config files
#
# Run once:           gaal sync
# Run as service:     gaal sync --service --interval 10m
# Check state:        gaal status
# Discover installed: gaal audit
# Validate schema:    gaal schema -f schema.json
#
# Full reference:     docs/quick_start.md`
	} else {
		body = `# Configure gaal behaviour (telemetry, future settings).
# The repositories, skills, and mcps sections are not shown here but are
# supported — add them manually if you need scope-wide defaults.
#
# Full reference:     docs/quick_start.md`
	}
	return "# gaal.yaml — generated by \"gaal init\"\n" +
		"# Scope level: " + scopeLabel(scope) + "\n" +
		"#\n" +
		body + "\n\n" +
		"# gaal config schema version — stable forever.\n" +
		"schema: 1\n\n"
}

// sectionDef describes one top-level section of the config template.
type sectionDef struct {
	key         string       // yaml key name
	structType  reflect.Type // Go struct whose tags drive the Fields: block
	emptyVal    string       // written after the header (e.g. "{\n  \n}" or "[\n\n]")
	headerLines []string     // static narrative lines after the section title
	enumLabel   string       // label for the "Supported X:" line (empty = skip)
	enumField   string       // yaml key of the field whose Enums to display
	agentNote   bool         // when true, append the Supported agents note
	example     []string     // lines inside the Example: block
}

var sections = []sectionDef{
	{
		key:        "repositories",
		structType: reflect.TypeOf(config.ConfigRepo{}),
		emptyVal:   "{\n  \n}",
		headerLines: []string{
			"Clone or update local copies of remote repositories.",
			"Keys are local destination paths (relative to the working directory or absolute).",
		},
		enumLabel: "Supported types",
		enumField: "type",
		example: []string{
			"  src/my-service:",
			"    type: git",
			"    url: https://github.com/my-org/my-service.git",
			"    version: main",
		},
	},
	{
		key:        "skills",
		structType: reflect.TypeOf(config.ConfigSkill{}),
		emptyVal:   "[\n\n]",
		headerLines: []string{
			"Download and install SKILL.md collections into AI agent directories.",
			"",
			"Sources:",
			"  - GitHub shorthand:  owner/repo",
			"  - Full URL:          https://github.com/owner/repo",
			"  - SSH:               git@github.com:owner/repo.git",
			"  - Local path:        ./path/to/skills  or  ~/my-skills",
		},
		agentNote: true,
		example: []string{
			"  - source: vercel-labs/agent-skills",
			`    agents: ["*"]`,
			"    global: false",
		},
	},
	{
		key:        "mcps",
		structType: reflect.TypeOf(config.ConfigMcp{}),
		emptyVal:   "[\n\n]",
		headerLines: []string{
			"Upsert MCP (Model Context Protocol) server entries into agent JSON config files.",
			"Existing entries in the target file are preserved; only the named key is updated.",
		},
		example: []string{
			"  - name: filesystem",
			`    agents: ["claude-code"]`,
			"    global: true",
			"    inline:",
			"      command: uvx",
			"      args: [mcp-server-filesystem, /home/user/projects]",
		},
	},
}

// Generate produces the complete gaal.yaml / config.yaml template as a byte
// slice. It is the drop-in replacement for the embedded init_template.yaml.
// The Fields: block for each section is derived automatically from the config
// struct tags — adding or renaming a field on Config* updates the template
// without any manual change here.
// The scope is annotated in the file header (e.g. "# Scope level: User").
//
// For Workspace scope all three resource sections (repositories, skills, mcps)
// are emitted. For User and Global scopes only the top-level gaal behaviour
// fields (those tagged gaal:"maxscope=user" or gaal:"maxscope=global") are
// written as documented YAML keys with their default values.
func Generate(scope config.ConfigScope) ([]byte, error) {
	slog.Debug("generating config yaml template", "scope", scope)
	var buf bytes.Buffer
	buf.WriteString(buildIntro(scope))
	if scope == config.ScopeWorkspace {
		for _, sec := range sections {
			writeSection(&buf, sec)
		}
	} else {
		writeBehaviourFields(&buf)
	}
	return buf.Bytes(), nil
}

// writeBehaviourFields emits the top-level Config fields that carry a
// gaal:"maxscope=..." tag as commented YAML keys with their zero/default value.
// These are the only gaal-behaviour settings relevant in User/Global configs.
// New fields added to Config with a maxscope tag are picked up automatically.
func writeBehaviourFields(buf *bytes.Buffer) {
	slog.Debug("writing behaviour fields for non-workspace template")
	fields := Reflect(reflect.TypeOf(config.Config{}))
	for _, f := range fields {
		if f.MaxScope == "" || f.Deprecated {
			continue
		}
		// Emit a descriptive comment then the key with its zero value.
		buf.WriteString("# " + f.Description + "\n")
		buf.WriteString(f.YAMLKey + ": false\n")
		buf.WriteString("\n")
	}
}

// writeSection emits one complete config section (separator + header + Fields:
// + Example: + separator + key: emptyVal) into buf.
func writeSection(buf *bytes.Buffer, sec sectionDef) {
	slog.Debug("writing template section", "key", sec.key)

	fields := Reflect(sec.structType)

	buf.WriteString(separator + "\n")
	buf.WriteString("# " + sec.key + "\n")
	buf.WriteString("#\n")

	// Static narrative lines.
	for _, line := range sec.headerLines {
		if line == "" {
			buf.WriteString("#\n")
		} else {
			buf.WriteString("# " + line + "\n")
		}
	}

	// Optional "Supported types: git, hg, ..." line driven by enum tags.
	if sec.enumLabel != "" && sec.enumField != "" {
		enums := findEnums(fields, sec.enumField)
		if len(enums) > 0 {
			buf.WriteString("#\n")
			buf.WriteString("# " + sec.enumLabel + ": " + strings.Join(enums, ", ") + "\n")
		}
	}

	// Fields block — auto-generated from struct tags.
	buf.WriteString("#\n")
	buf.WriteString("# Fields:\n")
	for _, f := range fields {
		if f.Deprecated {
			continue
		}
		req := "optional"
		if f.Required {
			req = "required"
		}
		buf.WriteString(fmt.Sprintf("#   %-8s— %s (%s)\n", f.YAMLKey+" ", f.Description, req))

		// One level of sub-fields (e.g. inline → ConfigMcpItem).
		for _, sf := range f.SubFields {
			if sf.Deprecated {
				continue
			}
			sreq := "optional"
			if sf.Required {
				sreq = "required"
			}
			buf.WriteString(fmt.Sprintf("#     %-8s— %s (%s)\n", sf.YAMLKey+" ", sf.Description, sreq))
		}
	}

	// Optional supported-agents note — generated from the agent registry.
	if sec.agentNote {
		buf.WriteString("#\n")
		for _, line := range buildAgentsNote() {
			buf.WriteString(line + "\n")
		}
	}

	// Example block.
	buf.WriteString("#\n")
	buf.WriteString("# Example:\n")
	for _, line := range sec.example {
		buf.WriteString("# " + line + "\n")
	}

	buf.WriteString(separator + "\n")
	buf.WriteString(sec.key + ": " + sec.emptyVal + "\n")
	buf.WriteString("\n")
}

// buildAgentsNote returns the "# Supported agents: ..." comment lines built
// from the live agent registry so the list is always up to date.
func buildAgentsNote() []string {
	names := agent.Names()
	sort.Strings(names)

	const prefix = "# Supported agents: "
	const indent = "#   "
	const maxWidth = 79 // characters per line including the leading "# "

	var lines []string
	var cur strings.Builder
	cur.WriteString(prefix)

	for i, name := range names {
		var seg string
		if i == 0 {
			seg = name
		} else {
			seg = ", " + name
		}
		if i > 0 && cur.Len()+len(seg) > maxWidth {
			lines = append(lines, cur.String())
			cur.Reset()
			cur.WriteString(indent)
			seg = name
		}
		cur.WriteString(seg)
	}
	if cur.Len() > len(indent) || (len(lines) == 0 && cur.Len() > len(prefix)) {
		lines = append(lines, cur.String())
	}
	lines = append(lines, `#   (run "gaal info agent" for the full list)`)
	return lines
}

// findEnums returns the Enums slice from the field matching yamlKey.
func findEnums(fields []FieldSpec, yamlKey string) []string {
	for _, f := range fields {
		if f.YAMLKey == yamlKey {
			return f.Enums
		}
	}
	return nil
}
